### ISSUE TITLE
Executing goesf binary gets Killed: 9

### ISSUE THREAD

**Issue by 0xmachos** [xorrior/goesf#1]
## Environment Info
macOS Version: `10.15`
macOS Build: `19A582a`
Go Version: `go1.13.3 darwin/amd64`

## Issue
I'm not very familiar with Go so apologies if this is a n00b question and I'm missing something obvious. 

I build then sign with my Mac Developer ID however when I try to execute the binary (even with `sudo`) it gets killed. 

```
$ ./goesf 
Killed: 9
```

## Signing 
I have an Apple Developer account. I followed the signing instructions you listed in the README. Below is what I did with some redactions. 

```
security find-identity -v -p codesigning
  1) 8CXXXXXXXXXXXX1B "Mac Developer: MXXXX XXXXX (2XXXXXXXX)"
  2) 2EXXXXXXXXXXXX57 "Apple Development: MXXXX XXXXX (2XXXXXXXX)"
     2 valid identities found
```
I used the Mac Developer identity to sign the binary.
```
codesign -s '8CXXXXXXXXXXXX1B' --entitlements entitlements.xml goesf 
```

**Comment by xorrior** [comment]
You need to disable SIP
